class StarkError(Exception): ...
class InputErrors(StarkError):
    def __init__(self, content: list[dict[str, str]]) -> None: ...
class InternalServerError(StarkError):
    def __init__(self, message: str = ...) -> None: ...
class UnknownError(StarkError):
    def __init__(self, message: str) -> None: ...
class InvalidSignatureError(StarkError):
    def __init__(self, message: str) -> None: ...
